### ISSUE TITLE
Open PRs tab blank

### ISSUE THREAD

**Issue by rempsyc** [easystats/dashboard#13]
https://easystats.github.io/dashboard/dashboard.html#open-prs

The Open PRs tab doesn't work for me (it's blank). All other tabs work fine. Anybody else?

**Comment by etiennebacher** [comment]
I did that voluntarily. At some point, because of some timeout (maybe because my account couldn't fetch as much github data as needed, all runs were failing (so I always notifications about this as well). The issue always occurred in the PR tab, so I decided to hide this tab if I couldn't get the data but still show the rest.

https://github.com/easystats/dashboard/commit/7f0389bff319a3143f2846bb69bc3139747e1b7e

**Comment by etiennebacher** [comment]
If this can be fixed with the new token in #12, then it can be reverted

**Comment by rempsyc** [comment]
Checking if now is a better time to reactivate the PR tab. Happy to do it if you can point me where to go :)

**Comment by etiennebacher** [comment]
I just tried to revert the commit that deactivated this tab: 9ced999f296766af251f9d9f5626b69407b2039e

If it doesn't work then I don't know what to do

**Comment by rempsyc** [comment]
Omg it's working :D

https://easystats.github.io/dashboard/dashboard.html#open-prs

Thanks @etiennebacher !

**Comment by etiennebacher** [comment]
Actually it doesn't

![image](https://github.com/easystats/dashboard/assets/52219252/86e7bdd7-ad38-49f7-9bb0-9321ffa58401)

It worked once last week but didn't get updated since (all the PRs about adding a "Getting help" page are displayed but they were merged days ago).

**Comment by etiennebacher** [comment]
Last scheduled push worked, I'm closing this. Thanks for reviving this issue, I would have probably let it aside for a while
